"""Terraform generator.

Scaleway locations are emitted with native resources of the
``scaleway/scaleway`` provider (Kapsule cluster, pools, private network,
artefact bucket). Other providers are emitted as calls to local modules
whose stubs are generated with explicit TODOs: the consortium or the
provider owner fills them, the DSL does not need to change (extensibility).
Run ``terraform init && terraform validate`` on the output before any use.
"""
from __future__ import annotations

from collections import defaultdict

from amlops.dsl.model import ResolvedPipeline
from amlops.placement.optimizer import Placement

from . import GeneratedFile, ident, register_generator, slug

# Illustrative mapping of catalogue instance types to Scaleway node types.
SCW_NODE_TYPES = {"cpu-4": "PRO2-XS", "cpu-16": "PRO2-M", "gpu-l4": "L4-1-24G"}


def _pools(rp: ResolvedPipeline, placement: Placement) -> dict[str, dict[str, dict]]:
    """location -> itype -> {max_nodes, steps}"""
    steps = {s.id: s for s in rp.steps}
    out: dict[str, dict[str, dict]] = defaultdict(dict)
    for sid, o in placement.assignment.items():
        pool = out[o.location].setdefault(o.itype, {"max_nodes": 0, "steps": [], "continuous": 0})
        s = steps[sid]
        n = max(1, -(-s.resources.vcpu // o.vcpu))
        pool["steps"].append(sid)
        if s.continuous:
            pool["continuous"] += n * s.replicas
        pool["max_nodes"] = max(pool["max_nodes"], n * (s.replicas if s.continuous else 1))
    for loc in out:
        for p in out[loc].values():
            p["max_nodes"] = max(p["max_nodes"], p["continuous"]) + 1
    return out


@register_generator("terraform")
def generate_terraform(rp: ResolvedPipeline, placement: Placement) -> list[GeneratedFile]:
    pools = _pools(rp, placement)
    name = slug(rp.name)
    providers = sorted({loc.split("/")[0] for loc in pools})
    req = []
    if "scaleway" in providers:
        req.append('    scaleway = {\n      source  = "scaleway/scaleway"\n      version = ">= 2.40"\n    }')
    main = [
        f"# Generated by amlops from pipeline '{rp.name}'. Do not edit by hand: edit the DSL model.",
        "terraform {",
        '  required_version = ">= 1.6"',
        "  required_providers {",
        *req,
        "  }",
        "}",
        "",
        'variable "k8s_version" {\n  type    = string\n  default = "1.31"\n}',
        "",
    ]
    files: list[GeneratedFile] = []
    realised: list[str] = []
    for loc, itypes in sorted(pools.items()):
        provider, region = loc.split("/")
        lid = ident(loc)
        realised += [f"step:{s}" for p in itypes.values() for s in p["steps"]]
        if provider == "scaleway":
            main += [
                f'provider "scaleway" {{\n  alias  = "{lid}"\n  region = "{region}"\n}}',
                "",
                f'resource "scaleway_vpc_private_network" "{lid}" {{\n  provider = scaleway.{lid}\n'
                f'  name     = "{name}-{slug(region)}-pn"\n}}',
                "",
                f'resource "scaleway_k8s_cluster" "{lid}" {{\n  provider                    = scaleway.{lid}\n'
                f'  name                        = "{name}-{slug(region)}"\n  version                     = var.k8s_version\n'
                f'  cni                         = "cilium"\n  private_network_id          = scaleway_vpc_private_network.{lid}.id\n'
                f'  delete_additional_resources = true\n  tags                        = ["amlops", "{name}"]\n}}',
                "",
            ]
            for itype, p in sorted(itypes.items()):
                main.append(
                    f'resource "scaleway_k8s_pool" "{lid}_{ident(itype)}" {{\n  provider    = scaleway.{lid}\n'
                    f'  cluster_id  = scaleway_k8s_cluster.{lid}.id\n  name        = "{slug(itype)}"\n'
                    f'  node_type   = "{SCW_NODE_TYPES[itype]}"\n  size        = {max(1, p["continuous"])}\n'
                    f'  autoscaling = true\n  min_size    = {p["continuous"]}\n  max_size    = {p["max_nodes"]}\n'
                    f'  tags        = ["steps:{"+".join(p["steps"])}"]\n}}\n'
                )
            main += [
                f'resource "scaleway_object_bucket" "{lid}_artifacts" {{\n  provider = scaleway.{lid}\n'
                f'  name     = "{name}-{slug(region)}-artifacts"\n  versioning {{\n    enabled = true\n  }}\n}}',
                "",
                f'output "{lid}_kubeconfig" {{\n  value     = scaleway_k8s_cluster.{lid}.kubeconfig[0].config_file\n'
                f'  sensitive = true\n}}',
                "",
            ]
        else:
            pool_lines = ",\n".join(
                f'    {{ name = "{slug(t)}", instance_type = "{t}", min = {p["continuous"]}, max = {p["max_nodes"]} }}'
                for t, p in sorted(itypes.items()))
            main += [
                f'module "{lid}" {{\n  source       = "./modules/{provider}-k8s"\n  cluster_name = "{name}-{slug(region)}"\n'
                f'  region       = "{region}"\n  k8s_version  = var.k8s_version\n  node_pools = [\n{pool_lines}\n  ]\n}}',
                "",
            ]
            files.append(GeneratedFile(
                f"terraform/modules/{provider}-k8s/main.tf",
                f"# Module stub for provider '{provider}'.\n"
                "# TODO(provider owner): implement a managed Kubernetes cluster, node pools mapped from\n"
                "# catalogue instance types, and an S3-compatible versioned artefact bucket.\n"
                'variable "cluster_name" { type = string }\nvariable "region" { type = string }\n'
                'variable "k8s_version" { type = string }\n'
                'variable "node_pools" {\n  type = list(object({ name = string, instance_type = string, min = number, max = number }))\n}\n'
                'output "kubeconfig" {\n  value     = null\n  sensitive = true\n}\n',
                realises=[f"provider:{provider}"], activities=["O2"]))
    files.insert(0, GeneratedFile("terraform/main.tf", "\n".join(main) + "\n", realises=realised + ["placement"],
                                  activities=["O2", "D8", "M9"]))
    return files
